# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thomas Tu
website: thomastu.github.io
author:
    email: ttu@energy-solution.com
    name: Thomas Tu
    phone: (415) 568 0509
    twitter:
        username: thomasthetutu
    github:
        username: thomastu
    stackoverflow:
        userid: "4267783"
        username: thtu
description: Personal site to discuss my public facing projects and an up-to-date resume.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thomastu.github.io" # the base hostname & protocol for your site

# Build settings
# Where things are
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

# Handling Reading
exclude: [Gemfile, README.md]

# Plugins
plugins:
  - jekyll-paginate

# Outputting
permalink: /post/:title/
paginate: 5
paginate_path: '/blog/page/:num/'

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
