# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thomas Tu
email: ttu@lbl.gov
phone: (415) 568 0509
address: 2153 Virginia St. Berkeley CA, 94709
description: Personal site to discuss my public facing projects and an up-to-date resume.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thomastu.github.io" # the base hostname & protocol for your site
twitter_username: thomasthetutu
github_username:  thomastu
stackoverflow_userid: "4677586"
stackoverflow_username: thomas-tu

# Build settings
markdown: kramdown
